### ISSUE TITLE
XMPPComponent is not working: connect() got an unexpected keyword argument 'use_tls'

### ISSUE THREAD

**Issue by andreymal** [mathieui/slixmpp#1]
Just run echo example from [documentation](http://slixmpp.readthedocs.org/getting_started/component.html):
```
Component JID: echo.example.com
Password: 
Server: example.com
Port: 25000
Traceback (most recent call last):
  File "echo.py", line 104, in <module>
    xmpp.connect()
  File "/usr/lib/python3.4/site-packages/slixmpp/componentxmpp.py", line 113, in connect
    reattempt=reattempt)
TypeError: connect() got an unexpected keyword argument 'use_tls'
```

**Comment by mathieui** [comment]
Sorry, I did not intend for the bug tracker to be open on github, I’ll close it, but I created the bug on the [real bt](https://dev.louiz.org/issues/3093) at http://dev.louiz.org/projects/slixmpp
